[package]
name = "bevy_jam_2"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.8"
bevy_rapier2d = "0.16.1"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1
